version: "3.9"

services:

  aurastream-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aurastream-api
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    networks:
      - proxy

networks:
  proxy:
    external: true